services:
  # The Database Service
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    environment:
      SA_PASSWORD: "Charisma1997"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      # This saves the database data so it isn't lost
      - mssql_data:/var/opt/mssql

  # The API Service
  backend:
    container_name: backend_api
    build:
      # Tells Docker to look for the recipe in the './backend' folder
      context: ./backend
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy:-${HTTP_PROXY}}
        https_proxy: ${https_proxy:-${HTTPS_PROXY}}
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=database;Database=LinkShortenerDb;User Id=sa;Password=Charisma1997;TrustServerCertificate=True;
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=http://localhost:8080
      - Jwt__Audience=http://localhost:8080
    depends_on:
      - database

  # The Frontend Service
  frontend:
    container_name: frontend_web
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy:-${HTTP_PROXY}}
        https_proxy: ${https_proxy:-${HTTPS_PROXY}}
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend

volumes:
  mssql_data:
